# Aufgabe 1: Python-Tutorial
*Hinweis*: Auch wenn Sie schon Erfahrung mit Python haben, sollten Sie das Tutorial dennoch durchlesen. Da die folgenden Aufgaben stärker auf die selbstständige Lösung und die Arbeit mit der Dokumentation setzen, ist eine gute Grundlage Voraussetzung.

## Interaktive Notizbücher
In dieser Übung werden wir mit interaktiven Notizbüchern arbeiten. Hier sind Code und Text in einem Dokument gemischt. Einzelne Abschnitte oder auch *Zellen* können entweder Code oder Text enthalten. Codezellen können jederzeit ausgeführt werden. Dazu können die Schaltflächen neben den jeweiligen Zellen, die Symbolleiste oder die Tastenkombination <span class="label label-default">⇧</span> + <span class="label label-default">⏎</span> verwendet werden.

Probieren Sie aus, die folgende Codezelle auszuführen:

In [1]:
print('Hello World')

Hello World


### Reihenfolge
Neben der Codezeile wird eine laufende Nummer für jede Ausführung angezeigt. Es ist wichtig auf die Reihenfolge der Ausführung zu achten, insbesondere wenn globale Variablen betroffen sind. Schauen Sie in den folgenden Zellen, wie die Ausführungsreihenfolge die Ausgabe beeinflusst, und beobachten Sie die laufenden Nummern:

In [2]:
a = 4

In [3]:
a = a * 2

In [4]:
a = 3

In [5]:
print(a)

3


### Ausgabe
Zusätzlich zur Ausgabe durch Funktionen wie `print` wird nach der Ausführung der Wert des Ausdrucks letzten Zeile angezeigt, solange es nicht der leere Wert ist. Das ist zum Beispiel bei Zuweisungen und Funktionsaufrufen ohne Rückgabewert der Fall.

In [6]:
a

3

### Zurücksetzen
Der Python-Prozess, der die Codezellen ausführt, wird auch *Kernel* genannt. Falls der Kernel abstürzt oder einen unbrauchbaren Zustand erreicht hat, kann er über das Kernel-Menu zurückgesetzt werden. Dabei können auch die Ausgaben unter den Codezellen entfernt werden. Falls nur die Ausgaben entfernt werden sollen, ist das Cell-Menü die richtige Wahl.

Um ein Notizbuch einmal komplett wie ein Programm auszuführen, können Sie die Option *Restart & Run All* verwenden. Sie sollten in den späteren Übungen darauf achten, dass das mit ihren Notizbüchern möglich ist und auch zu korrekten Ergebnissen führt.

## Python als Programmiersprache
Es gibt mehrere Gründe für die aktuelle Beliebtheit von Python in Forschung und Lehre. Einerseits ist die Sprache selbst einfach gehalten und intuitiv verständlich, aber gleichzeitig sehr ausdrucksstark. Andererseits ist das Ökosystem um Python gut aufgestellt. Bibliotheken sind einfach zu installieren und vielfältig verfügbar.

In dieser Übung setzen wir die aktuelle Version Python 3 ein. Viele ältere Projekte sind in der Version 2 programmiert, zu welcher die aktuelle Variante *nicht* abwärtskompatibel ist.

Im Folgenden soll ein kurzer Überblick über die Sprache gegeben werden. Für weitere Übungen ist das Buch  [The Python Workbook](https://www.springer.com/de/book/9783319142395) empfehlenswert. Aufgrund seiner Konzeption ist Python gut für "learning by doing" geeignet und dieser Ansatz wird auch in der Übung verfolgt - daher beschränkt sich diese Aufgabe auf die wesentlichen Elemente.

### Syntax
Im Studium werden Sie sich mit C und Java beschäftigt haben, die beide eine ähnliche Syntax zueinander aufweisen. Zu diesen Gemeinsamkeiten gehört auch, dass Whitespace (also Leerzeichen, Tabs und Zeilenumbrüche) keinen Einfluss auf das Programm hat. Bei Python ist Whitespace ein essentieller Bestandteil der Syntax. Einzelne Anweisungen werden nicht durch ein Semikolon getrennt, sondern durch einen Zeilenumbruch.

Um Blöcke zu strukturieren, verwendet Python **Einrückungen** statt Klammern. Ein Block wird normalerweise durch einen `:` am Ende der vorherigen Zeile eingeleitet:

In [7]:
a = 15
b = 12
if a > b:
    print('A ist größer als B!')
    b = a + 1
print('B ist größer als A!')

A ist größer als B!
B ist größer als A!


Aufgrund der Einrückung ist leicht zu erkennen, wo der Block endet. Während ein schlecht oder nicht eingerücktes C-Programm nur unleserlich ist, würde es in Python nicht einmal der Syntax entsprechen.

**Anweisungen** können beliebige Ausdrücke sein. Wichtig sind dabei vor allem **Zuweisungen**. Eine Besonderheit von Python ist, das Variablen vor der Verwendung nicht deklariert werden müssen:

In [8]:
a = 3

**Funktionsaufrufe** sind auch Anweisungen:

In [9]:
max(3,5)

5

Mit **Klammern** und **Operatoren** lassen sich beliebige Ausdrücke zusammensetzen.

In [10]:
a = 4 + (3 - 18)
b = True and (not False) and (a > 5)

Mit `#` lassen sich Kommentarzeilen einleiten. Mehrzeilige Kommentare werden mit `"""` umschlossen, sind aber eigentlich mehrzeilige Zeichenketten:

In [11]:
# Eine Kommentarzeile
""" Noch zwei
    Kommentarzeilen """
# Wieder ein Kommentar
a = """ Das ist eigentlich kein Kommentar, sondern
        eine mehrzeilige Zeichenkette :) """

### Grundlegende Datentypen
Python ist eine Sprache mit dynamischen Datentypen. Variablen müssen nicht mit festem Typen deklariert werden und können sich auch zur Laufzeit ändern. Dennoch existiert das Konzept von Typen in Python und sie können auch explizit verwendet werden. Folgende grundlegende Datentypen gibt es:

**Zeichenketten** `str` können mit einfachen oder doppelten Anführungszeichen umschlossen werden. Die beiden Varianten sind absolut gleichwertig:

In [12]:
a = "Dies ist eine Zeichenkette."
a = 'Dies ist eine Zeichenkette.'
type(a)

str

**Ganze Zahlen** `int` können in vielen Stellenwertsystemen angegeben werden:

In [13]:
a = 12
a = 0xC
a = 0b1100
a = 0o14
type(a)

int

**Gleitkommazahlen** `float` können mit Dezimalpunkt `.` oder in wissenschaftlicher Notation geschrieben werden:

In [14]:
a = 1.3726
a = 8.4e-7
type(a)

float

**Boolesche Werte** `bool` können `True` oder `False` sein:

In [15]:
a = True
a = not a
type(a)

bool

Zuletzt gibt es noch das Schlüsselwort `None`, das für **leere Ausdrücke** steht. Es ist vergleichbar mit dem `null`-Literal aus Java.

In [16]:
type(None)

NoneType

### Komplexe Datentypen
Zusätzlich zu diesen grundlegenden Datentypen gibt es noch einige komplexe Datentypen, die mehrere Werte zusammenfassen können.

Es gibt **Listen** `list`, die folgendermaßen definiert werden:

In [3]:
a = [1,2,3,4]

Die Funktion `len` ordnet einer Liste ihre Länge zu:

In [4]:
len(a)

4

Um auf einen oder mehrere Werte in einer Liste zuzugreifen, verwenden Sie die eckigen Klammern `[ ]` mit einem **Index**. Python indiziert Listen ab `0`, wobei zusätzlich `-1` auf das letzte Element verweist, `-2` auf das vorletzte und so weiter:

In [19]:
a = [4,3,5,7,6,0,1]

print(a[0])
a[2] = 3
print(a[2])
print(a[-2])

4
3
0


Für den Zugriff auf mehrere Werte kann mit `[` *anfang* `:` *ende* `]` ein **Bereich** angegeben werden, wobei *ende* das erste *nicht* enthaltene Element bezeichnet. Werden *anfang* oder *ende* weggelassen, wird der Bereich in die entsprechende Richtung so groß wie möglich gewählt.

In [20]:
a = [4,3,5,7,6,0,1]

print(a[5:7])
print(a[:1])
a[3:5] = [0, 0]
print(a[4:])

[0, 1]
[4]
[0, 0, 1]


Neben Listen gibt es noch **Tupel** `tuple`. Auf diese kann nur lesend zugegriffen werden. Sie eignen sich besonders, um Daten verschiedener Typen zu strukturieren. Bei Tupeln können die Klammern je nach Situation auch weggelassen werden, z.B. bei Zuweisungen.

In [21]:
a = ('Hamburger', 450)
b = 'Veggieburger', 435
type(b)

tuple

Der **Formatierungsoperator** `%` erwartet auf der linken Seite eine Zeichenkette mit einem Format. Auf der rechten Seite wird ein Tupel übergeben, wobei hier die Klammer *nicht* weggelassen werden können, weil der `%`-Operator dem Komma vorgezogen wird.

In [22]:
message = "Der %s wiegt %d Gramm."
print(message % a)
print(message % b)
print(message % ('Cheeseburger', 530))  # Hier müssen Klammern hin

Der Hamburger wiegt 450 Gramm.
Der Veggieburger wiegt 435 Gramm.
Der Cheeseburger wiegt 530 Gramm.


Tupel können außerdem auch auf der linken Seite von Zuweisungen eingesetzt werden, um **Mehrfachzuweisungen** vorzunehmen:

In [23]:
a, b = 12, 4
print(a)
print(b)

12
4


Eine weitere, etwas dynamischere Struktur ist das **Dictionary** `dict`. Es ist eine Sammlung von Schlüssel-Wert-Paaren, wobei ein Schlüssel als Index für den Zugriff auf den Wert verwendet wird. Für Schlüssel und Werte können jeweils beliebige Typen verwendet werden.

In [24]:
a = {'Name': 'Max Mustermann', 4711: True, False: [1,2,3]}
print(a[4711])
print(a['Name'])
print(a[False])

True
Max Mustermann
[1, 2, 3]


### Kontrollstrukturen
Python arbeitet Anweisungen grundsätzlich Zeile für Zeile der Reihe nach ab. Der Programmfluss kann wie in den meisten Programmiersprachen durch Verzweigungen und Wiederholungen kontrolliert werden.

**Verzweigungen** knüpfen die Ausführung von Anweisungen an eine Bedingung. Sie werden durch die Schlüsselwörter `if`, `elif` und `else` beschrieben:

In [25]:
if 301 % 45 == 31:
    print('Rest 31')
elif 301 % 45 == 18:
    print('Rest 18')
else:
    print('Anderer Rest')

Rest 31


**Wiederholungen** können in Form von `for`- und `while`-Schleifen auftreten.
Beide Schleifen können mit `break` beendet werden und überspringen mit `continue` einen Durchlauf. Die `for`-Schleife erwartet als Argument einen Ausdruck, der durchlaufen werden kann. Das kann zum Beispiel eine Liste oder ein Tupel sein. Die `while`-Schleife prüft vor jedem Durchlauf eine Bedingung:

In [26]:
for food in ['Hamburger', 'Cheeseburger', 'Veggieburger']:
    print('I like ' + food)
    
    i = 3
    while i > 0:
        if food == 'Cheeseburger':
            break  # Bricht die innere Schleife ab.
        print('Me too!')
        i -= 1

I like Hamburger
Me too!
Me too!
Me too!
I like Cheeseburger
I like Veggieburger
Me too!
Me too!
Me too!


Neben Listen können auch spezielle **Iteratoren** verwendet werden, um Programm effizienter zu gestalten. Mit `range` kann eine klassische von-bis-Schleife realisiert werden. Hier gilt wie für die Indizes, dass der Parameter für das Ende das erste *nicht* enthaltene Element beschreibt.

In [27]:
j = 0
for i in range(1, 5000000):
    j = i
print(j)

4999999


Weil wir hier einen speziellen Iterator verwendet haben, wird zu keiner Zeit eine Liste mit den Zahlen von 1 bis 4.999.999 gespeichert.

### Funktionen
In Python können mit dem Schlüsselwort `def` Funktionen definiert werden. Auch hier müssen weder für Argumente noch für Rückgabewerte Typen angegeben werden. Mit `return` können beliebige Werte zurückgegeben werden, insbesondere auch Tupel. Fehlt die `return`-Anweisung, wird `None` zurückgegeben.

In [28]:
def division_with_rest(dividend, divisor):
    rest = dividend
    result = 0
    while rest > divisor:
        result += 1
        rest -= divisor
    return result, rest

result17, rest17 = division_with_rest(17, 3)
print('Ergebnis: %d mit Rest %d' % (result17, rest17))

Ergebnis: 5 mit Rest 2


Für Funktionen können auch **Default**-Argumente angegeben werden. Damit die Reihenfolge für den Aufrufer nicht unübersichtlich wird, können die Argumente beim Aufruf auch benannt werden:

In [29]:
def fancy_function(first, second=2, third=3):
    print('%d, %d, %d' % (first, second, third))

fancy_function(1)
fancy_function(1, 18)
fancy_function(1, second=18)
fancy_function(1, third=-12)
fancy_function(second=13, first=1)

1, 2, 3
1, 18, 3
1, 18, 3
1, 2, -12
1, 13, 3


## Pakete


Python kommt mit einer reichhaltigen Auswahl an Zusatzbibliotheken. Außerdem gibt es ganze Distributionen wie [Anaconda](https://www.anaconda.com/download/), die mit einem komfortablen Paketmanager ausgeliefert werden. Dadurch können Python-Programme mit wenig Aufwand plattformunabhängig gemacht werden.

Um auf Funktionen außerhalb des eigenen Programms zuzugreifen, werden **Module** importiert. Module sind gewöhnliche Python-Programme, in denen Funktionen definiert werden. Da Python keine Zugriffsmodifizierer kennt, sind alle Funktionen öffentlich. Um Module zu importieren, wird die `import`-Anweisung verwendet:

In [30]:
import math
math.pi

3.141592653589793

Manche Pakete haben umständliche Namen. Daher können mit dem `as`-Schlüsswort `import`-Anweisungen um einen **Alias** ergänzt werden. Sie können so unter anderen Namen verwendet werden:

In [31]:
import statistics as stats
stats.mean([1,2])

1.5

Falls nur einzelne Funktionen aus einem Modul benötigt werden, können diese mit `from` in den globalen Namensraum importiert werden:

In [32]:
from random import randint
randint(1,3)

2

Auch hier sind Aliase möglich:

In [33]:
from random import choice as ch, uniform as uni
uni(3,5)

4.77698744227884

### Numpy
Im Paket `numpy` sind viele wichtige Funktionen und Typen für das wissenschaftliche Rechnen enthalten. Besonders wichtig sind die n-dimensionalen Arrays, durch die z.B. Bilder dargestellt werden können. So können viele Operationen in einer vektorisierten Schreibweise durchgeführt werden.

In [18]:
import numpy as np

Um ein **Array** zu erstellen, kann `ndarray` verwendet werden. Dazu muss die gewünschte Größe `shape` des Arrays angegeben werden. Es wird standardmaßig nicht mit Nullen initialisiert:

In [26]:
a = np.ndarray(shape=(2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


Alternativ können bestehende Listen oder verschachtelte Liste zu Arrays **konvertiert** werden. Dazu können die Funktionen `array` und `asarray` verwendet werden, wobei erstere die Daten kopiert während letzere die Daten nach Möglichkeit an der urprünglichen Stelle weiterverwendet:

In [36]:
a = [[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]]
b = np.array(a)
print(b.shape)

(2, 5)


Da das Array mehrere Dimensionen hat, können zum Zugriff auch **mehrdimensionale Indizes** verwendet werden:

In [37]:
print(b[0,2])

3


Indizes mit weniger Dimensionen führen zum Zugriff auf **Teilarrays**:

In [38]:
print(b[0])

[1 2 3 4 5]


Auch die Kombination mit **Bereichsindizes** ist erlaubt:

In [39]:
print(b[1,2:4])

[8 9]


Wenn dieselbe Operation auf mehrere Element eines Arrays angewandt werden soll, kann **Broadcasting** verwendet werden. Solange die rechte Seite einer Operation weniger Dimensionen oder in einer Dimension weniger Elemente hat als die linke, werden die Elemente der rechten Seite für die Operation passend vervielfältigt:

In [40]:
print(b * [[10],[-10]])
print(b * [1, -1, 1, -1, 1])
print(b * [3])

[[  10   20   30   40   50]
 [ -60  -70  -80  -90 -100]]
[[ 1 -2  3 -4  5]
 [ 6 -7  8 -9 10]]
[[ 3  6  9 12 15]
 [18 21 24 27 30]]


Nach diesem kurzen Überblick verfügen Sie über ausreichende Grundkenntnisse in der Programmiersprache Python. Falls Sie Interesse haben, die Sprache tiefgründiger zu lernen, besuchen Sie [learnpython.org](https://www.learnpython.org/). Dort finden Sie weiterführendes Material.